// Generated by CoffeeScript 1.6.2
(function() {
  var _ref, _ref1, _ref2, _ref3, _ref4,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  models.Plot = (function(_super) {
    __extends(Plot, _super);

    function Plot() {
      _ref = Plot.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    return Plot;

  })(Backbone.Model);

  models.Crop = (function(_super) {
    __extends(Crop, _super);

    function Crop() {
      _ref1 = Crop.__super__.constructor.apply(this, arguments);
      return _ref1;
    }

    Crop.prototype.MAX_HAPPINESS = 9;

    Crop.prototype.MAX_GROWTH = 9;

    Crop.prototype.GROW_THRESHOLD = 7;

    Crop.prototype.DIE_THRESHOLD = 5;

    Crop.prototype.GROWTH_PER_DAY = 1;

    Crop.prototype.defaults = {
      maxAge: 22,
      yieldAt: 10,
      maxHarvestSize: 4,
      thirst: 2,
      weather: 5,
      hardiness: 2,
      age: 0,
      watered: false,
      "yield": 0,
      harvestSize: 0,
      happiness: 0,
      growth: 0
    };

    Crop.prototype.initialize = function() {
      this.happiness = this.MAX_HAPPINESS;
      this.mods = new Backbone.Collection;
      return this.listenTo(time, 'dawn', this.onDayStart);
    };

    Crop.prototype.onDayStart = function() {
      debugger;      this.set({
        happiness: this.get('happiness') + (this.get('watered') && Math.abs(this.get('weather') - game.weather) < 2 ? +1 : -1)
      }, {
        silent: true
      });
      this.set({
        happiness: this.get('happiness').constrain(0, this.MAX_HAPPINESS)
      }, {
        silent: true
      });
      if (this.get('happiness') >= this.GROW_THRESHOLD && this.get('age') < this.get('maxAge')) {
        this.set({
          growth: this.get('growth') + this.GROWTH_PER_DAY
        }, {
          silent: true
        });
      }
      if (this.get('happiness') <= this.DIE_THRESHOLD || this.get('age') >= this.get('maxAge')) {
        this.set({
          growth: this.get('growth') - this.GROWTH_PER_DAY
        }, {
          silent: true
        });
      }
      /*
      		TODO When plants are at low health they take damage to one of their core attributes
      */

      this.set({
        age: this.get('age') + 1
      });
      if (this.get('age') >= this.get('yieldAt')) {
        this.set({
          'yield': this.get('yield') + Math.round((this.get('happiness') - 5) / 2)
        }, {
          silent: true
        });
      }
      this.set({
        watered: false
      }, {
        silent: true
      });
      return this.trigger('change');
    };

    Crop.prototype.water = function() {
      if (!this.prop.watered) {
        this.prop.watered = true;
        return true;
      }
      return false;
    };

    return Crop;

  })(Backbone.Model);

  views.Plot = (function(_super) {
    __extends(Plot, _super);

    function Plot() {
      _ref2 = Plot.__super__.constructor.apply(this, arguments);
      return _ref2;
    }

    Plot.prototype.tagName = 'div';

    Plot.prototype.initialize = function() {
      var _this = this;

      this.$el = $(this.el);
      this.model.bind('remove', function() {
        return _this.$el.remove();
      });
      this.el.id = this.cid;
      return this.$el.on({
        plant: function(e, plantType) {
          var crop, i, _i, _len, _ref3;

          _ref3 = _this.collection.models;
          for (i = _i = 0, _len = _ref3.length; _i < _len; i = ++_i) {
            crop = _ref3[i];
            if (crop.cid = _this.model.cid) {
              break;
            }
          }
          _this.collection.remove(_this.collection.at(i));
          return _this.collection.add(new models.Crop(CROPS[plantType]), {
            at: i
          });
        }
      });
    };

    Plot.prototype.render = function() {
      this.$el.html("<div class=\"plot\" id=\"" + this.cid + "\">Plot</div>");
      return this;
    };

    return Plot;

  })(Backbone.View);

  views.Crop = (function(_super) {
    __extends(Crop, _super);

    function Crop() {
      _ref3 = Crop.__super__.constructor.apply(this, arguments);
      return _ref3;
    }

    Crop.prototype.tagName = 'div';

    Crop.prototype.initialize = function() {
      this.$el = $(this.el);
      _.bindAll(this);
      this.$el.attr({
        id: this.cid,
        'class': 'crop'
      });
      this.listenTo(this.model, 'change', this.render);
      return this.render();
    };

    Crop.prototype.events = {
      water: 'water'
    };

    Crop.prototype.render = function() {
      this.$el.toggleClass('unwatered', !this.model.get('watered'));
      this.$el.html(this.template(this.model));
      return this;
    };

    Crop.prototype.water = function() {
      return this.model.set({
        watered: true
      });
    };

    Crop.prototype.template = _.template("<div><b><%@name%></b></div>\n<%=game.meterTemplate({width:80, height: 5, value: this.get('age') / this.get(\"maxAge\")})%>\n<div>Growth: <%@growth%></div>\n<%=game.meterTemplate({width:80, height: 5, bg: 'yellow', value: this.get('happiness') / this.MAX_HAPPINESS})%>\n<%if(this.get('yield')){%>Yield: <%@yield%><%}%>\n<%if(!this.get('watered')){%><div>thirsty</div><%}%>");

    return Crop;

  })(Backbone.View);

  views.Field = (function(_super) {
    __extends(Field, _super);

    function Field() {
      _ref4 = Field.__super__.constructor.apply(this, arguments);
      return _ref4;
    }

    Field.prototype.el = $('#field');

    Field.prototype.initialize = function() {
      this.$el = $(this.el);
      _.bindAll(this);
      this.collection.bind('add', this.appendItem);
      this.length = 0;
      this.el.id = this.cid;
      return this.render();
    };

    Field.prototype.events = {
      expand: 'expand'
    };

    Field.prototype.appendItem = function(crop) {
      var item_view;

      item_view = new views[crop.constructor.name]({
        model: crop
      });
      item_view.collection = this.collection;
      return this.$el.append(item_view.render().el);
    };

    Field.prototype.expand = function() {
      return this.collection.add(new models.Plot);
    };

    Field.prototype.render = function() {
      return this.$el.html('<div class="expand">Expand Garden</div>');
    };

    return Field;

  })(Backbone.View);

}).call(this);

/*
//@ sourceMappingURL=crops.map
*/
