// Generated by CoffeeScript 1.6.2
(function() {
  var bb, itemItter, _ref, _ref1, _ref2, _ref3, _ref4, _ref5,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  bb = Backbone;

  window.models || (window.models = {});

  window.collections || (window.collections = {});

  window.views || (window.views = {});

  itemItter = 0;

  models.Item = (function(_super) {
    __extends(Item, _super);

    function Item() {
      _ref = Item.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Item.prototype.defaults = {
      name: '',
      label: '',
      description: '',
      maxUses: 0,
      age: 0,
      color: 'blue',
      maxAge: 0
    };

    Item.prototype.initialize = function() {
      var init;

      init = this.get('initialize');
      if (init) {
        return init.call(this);
      }
    };

    return Item;

  })(bb.Model);

  models.Tool = (function(_super) {
    __extends(Tool, _super);

    function Tool() {
      _ref1 = Tool.__super__.constructor.apply(this, arguments);
      return _ref1;
    }

    Tool.prototype.defaults = {
      active: false,
      targets: ''
    };

    return Tool;

  })(models.Item);

  views.Item = (function(_super) {
    __extends(Item, _super);

    function Item() {
      _ref2 = Item.__super__.constructor.apply(this, arguments);
      return _ref2;
    }

    Item.prototype.tagName = 'div';

    Item.prototype.initialize = function() {
      var _this = this;

      _.bindAll(this);
      this.model.bind('change:targetable', function() {
        return $(_this.el).toggleClass('targetable', _this.model.get('targetable'));
      });
      $(this.el).attr({
        id: 'item_' + this.model.cid,
        'data-itemid': this.model.get('id'),
        'class': 'item ' + this.model.get('name')
      });
      this.listenTo(time, 'change:hours', this.render);
      if (this.model.get('use')) {
        return $(this.el).on({
          click: this.model.get('use')
        });
      }
    };

    Item.prototype.render = function() {
      $(this.el).html(this.template(this.model));
      return this;
    };

    Item.prototype.template = _.template("<div><%@label%></div>\n<%@description%>\n<%if(this.get('maxUses')){%>\n	<%=game.meterTemplate({width:60, height: 5, bg: this.get('color'), value: this.get('uses') / this.get('maxUses')})%>\n<%}%>");

    return Item;

  })(bb.View);

  views.Tool = (function(_super) {
    __extends(Tool, _super);

    function Tool() {
      _ref3 = Tool.__super__.constructor.apply(this, arguments);
      return _ref3;
    }

    Tool.prototype.initialize = function() {
      var _this = this;

      Tool.__super__.initialize.call(this);
      this.$el = $(this.el);
      $(this.el).addClass('tool');
      this.model.bind('change:active', this.changeActive);
      this.model.bind('change:uses', this.render);
      $(this.el).on({
        click: function(e) {
          return _this.model.set({
            active: true
          });
        }
      });
      return this;
    };

    Tool.prototype.changeActive = function() {
      var key, model, val, _i, _len, _ref4, _ref5, _results;

      if (this.model.get('active')) {
        console.log(this.model.get('name') + ' activated');
        _ref4 = player.inventory.models;
        for (_i = 0, _len = _ref4.length; _i < _len; _i++) {
          model = _ref4[_i];
          if (model.cid !== this.model.cid) {
            model.set({
              active: false
            });
          }
        }
        $(this.el).addClass('active');
        _ref5 = this.model.get('actions');
        _results = [];
        for (key in _ref5) {
          val = _ref5[key];
          $(key).addClass('targetable');
          _results.push($d.on('click.' + this.cid, key, val.bind(this.model)));
        }
        return _results;
      } else {
        for (key in this.model.get('actions')) {
          $(key).removeClass('targetable');
        }
        $(this.el).removeClass('active');
        return $d.off('click.' + this.cid);
      }
    };

    Tool.prototype.render = function() {
      $(this.el).toggleClass('active', this.model.get('active'));
      return Tool.__super__.render.call(this);
    };

    return Tool;

  })(views.Item);

  collections.Inventory = (function(_super) {
    __extends(Inventory, _super);

    function Inventory() {
      _ref4 = Inventory.__super__.constructor.apply(this, arguments);
      return _ref4;
    }

    Inventory.prototype.model = models.Item;

    Inventory.prototype.initialize = function() {
      this.view = new views.Inventory({
        collection: this
      });
      this.bind('add', this.view.appendItem);
      this.addItem('bed');
      this.addItem('well');
      this.addTool('wateringCan');
      this.addTool('shovel');
      this.addTool('zucciniSeeds');
      this.view.render();
      return this;
    };

    Inventory.prototype.addItem = function(name) {
      var model, o;

      o = ITEMS[name];
      o.name = name;
      model = new models.Item(o);
      return this.add(model);
    };

    Inventory.prototype.addTool = function(name) {
      var o;

      o = TOOLS[name];
      o.name = name;
      return this.add(new models.Tool(o));
    };

    return Inventory;

  })(bb.Collection);

  views.Inventory = (function(_super) {
    __extends(Inventory, _super);

    function Inventory() {
      _ref5 = Inventory.__super__.constructor.apply(this, arguments);
      return _ref5;
    }

    Inventory.prototype.tagName = 'div';

    Inventory.prototype.initialize = function() {
      this.$el = $(this.el);
      _.bindAll(this);
      this.el.id = this.cid;
      return this;
    };

    Inventory.prototype.appendItem = function(item) {
      var item_view;

      item_view = new views[item.constructor.name]({
        model: item
      });
      return this.$el.append(item_view.render().el);
    };

    Inventory.prototype.render = function() {
      $('#inventory').empty().append(this.el);
      return this.el;
    };

    return Inventory;

  })(bb.View);

  itemItter = 0;

  window.Food = (function() {
    Food.prototype.status = 'fresh';

    function Food(name) {
      Food.__super__.constructor.call(this, FOOD, name);
      this;
    }

    Food.prototype.onDayStart = function() {
      var lastStatus;

      this.age += 1;
      lastStatus = this.status;
      if (this.age >= this.maxAge * .7) {
        this.status = 'wilted';
        if (lastStatus !== this.status) {
          return this.nutrition = this.nutrition * .7;
        }
      } else if (this.age >= this.maxAge * .9) {
        this.status = 'questionable';
        if (lastStatus !== this.status) {
          return this.nutrition = this.nutrition * .5;
        }
      } else if (this.age >= this.maxAge) {
        this.status = 'spoiled';
        return this.nutrition = -5;
      }
    };

    Food.prototype.template = _.template("<div class=\"item food action\" data-action=\"useitem\" data-actiondata='{\"id\":\"<%=id%>\"}'>\n	<h3><%=name%></h3>\n	<div class=\"status\"><%=status%></div>\n	<div class=\"nutrition\">Nutrition: <%=nutrition%></div>\n	<div class=\"protein\">Protein: <%=protein%></div>\n	<div class=\"calories\">Calories: <%=calories%></div>\n	<div class=\"description\"><%=description%></div>\n</div>");

    Food.prototype.render = function() {
      return this.template(this);
    };

    return Food;

  })();

}).call(this);

/*
//@ sourceMappingURL=items.map
*/
